import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { homepageQuoteSettingsSchema } from "@/lib/validation";
import { getHomepageQuoteCard, HOMEPAGE_QUOTE_CACHE_MS, resetHomepageQuoteCacheForTests } from "@/lib/homepage-quote";

test("homepage quote settings validation accepts a complete configuration", () => {
  const parsed = homepageQuoteSettingsSchema.safeParse({
    isQuoteCardVisible: true,
    isAutoGenerateActive: true,
    manualQuoteText: "A persistência abre espaço para novas respostas.",
    manualQuoteAuthor: "Teka Neves",
  });

  assert.equal(parsed.success, true);
});

test("homepage quote settings validation rejects empty manual fallback content", () => {
  const parsed = homepageQuoteSettingsSchema.safeParse({
    isQuoteCardVisible: true,
    isAutoGenerateActive: true,
    manualQuoteText: "",
    manualQuoteAuthor: "",
  });

  assert.equal(parsed.success, false);
});

test("schema declares homepage quote settings separately from inquiry data", async () => {
  const [schema, migration] = await Promise.all([
    readFile("prisma/schema.prisma", "utf8"),
    readFile("prisma/migrations/20260719213000_show_homepage_quote_by_default/migration.sql", "utf8"),
  ]);

  assert.match(schema, /model HomepageQuoteSettings/);
  assert.match(schema, /isQuoteCardVisible\s+Boolean\s+@default\(true\)/);
  assert.match(schema, /isAutoGenerateActive\s+Boolean\s+@default\(false\)/);
  assert.match(schema, /manualQuoteText\s+String/);
  assert.match(schema, /manualQuoteAuthor\s+String/);
  assert.match(migration, /UPDATE "HomepageQuoteSettings"[\s\S]*"isQuoteCardVisible" = true/);
});

test("homepage quote helper returns null when card is hidden", async () => {
  const quote = await getHomepageQuoteCard({
    now: 1000,
    settings: async () => ({
      isQuoteCardVisible: false,
      isAutoGenerateActive: false,
      manualQuoteText: "Frase manual",
      manualQuoteAuthor: "Autoria",
    }),
  });

  assert.equal(quote, null);
});

test("homepage quote helper returns manual quote when automatic mode is off", async () => {
  const quote = await getHomepageQuoteCard({
    now: 1000,
    settings: async () => ({
      isQuoteCardVisible: true,
      isAutoGenerateActive: false,
      manualQuoteText: "A pausa também trabalha por dentro.",
      manualQuoteAuthor: "Teka Neves",
    }),
  });

  assert.deepEqual(quote, {
    text: "A pausa também trabalha por dentro.",
    author: "Teka Neves",
    isAutoGenerated: false,
  });
});

test("homepage quote helper uses manual fallback when external quote translation fails", async () => {
  resetHomepageQuoteCacheForTests();
  const quote = await getHomepageQuoteCard({
    now: 2000,
    settings: async () => ({
      isQuoteCardVisible: true,
      isAutoGenerateActive: true,
      manualQuoteText: "Voltar a si também é movimento.",
      manualQuoteAuthor: "Teka Neves",
    }),
    fetchExternalQuote: async () => ({ text: "Keep going.", author: "Unknown" }),
    translateToPortuguese: async () => {
      throw new Error("TRANSLATION_FAILED");
    },
  });

  assert.deepEqual(quote, {
    text: "Voltar a si também é movimento.",
    author: "Teka Neves",
    isAutoGenerated: false,
  });
});

test("homepage quote helper caches automatic translated quote for one hour", async () => {
  resetHomepageQuoteCacheForTests();
  let calls = 0;
  const settings = async () => ({
    isQuoteCardVisible: true,
    isAutoGenerateActive: true,
    manualQuoteText: "Fallback",
    manualQuoteAuthor: "Teka Neves",
  });
  const fetchExternalQuote = async () => {
    calls += 1;
    return { text: `Keep going ${calls}.`, author: "Unknown" };
  };
  const translateToPortuguese = async (quote: { text: string; author: string }) => ({
    text: `Continue ${calls}.`,
    author: quote.author,
  });

  const first = await getHomepageQuoteCard({ now: 3000, settings, fetchExternalQuote, translateToPortuguese });
  const second = await getHomepageQuoteCard({ now: 3000 + HOMEPAGE_QUOTE_CACHE_MS - 1, settings, fetchExternalQuote, translateToPortuguese });
  const third = await getHomepageQuoteCard({ now: 3000 + HOMEPAGE_QUOTE_CACHE_MS + 1, settings, fetchExternalQuote, translateToPortuguese });

  assert.equal(calls, 2);
  assert.deepEqual(first, second);
  assert.deepEqual(third, { text: "Continue 2.", author: "Unknown", isAutoGenerated: true });
});
