import { prisma } from "@/lib/db";
import { homepageQuoteSettingsSchema } from "@/lib/validation";

export type ResolvedQuote = { text: string; author: string };
export type HomepageQuoteCardData = ResolvedQuote & { isAutoGenerated: boolean };
export type HomepageQuoteSettingsInput = {
  isQuoteCardVisible: boolean;
  isAutoGenerateActive: boolean;
  manualQuoteText: string;
  manualQuoteAuthor: string;
};

type HomepageQuoteSettings = HomepageQuoteSettingsInput;

export type HomepageQuoteResolverOptions = {
  now?: number;
  settings?: () => Promise<HomepageQuoteSettings>;
  fetchExternalQuote?: () => Promise<ResolvedQuote>;
  translateToPortuguese?: (quote: ResolvedQuote) => Promise<ResolvedQuote>;
};

export const HOMEPAGE_QUOTE_CACHE_MS = 60 * 60 * 1000;

const fallbackSettings: HomepageQuoteSettings = {
  isQuoteCardVisible: true,
  isAutoGenerateActive: false,
  manualQuoteText: "A escuta cuidadosa ajuda a abrir novos caminhos.",
  manualQuoteAuthor: "Teka Neves",
};

let cachedQuote: { quote: HomepageQuoteCardData; expiresAt: number } | null = null;

function manualQuote(settings: HomepageQuoteSettings): HomepageQuoteCardData {
  return {
    text: settings.manualQuoteText,
    author: settings.manualQuoteAuthor,
    isAutoGenerated: false,
  };
}

export function resetHomepageQuoteCacheForTests() {
  cachedQuote = null;
}

export async function getHomepageQuoteSettings(): Promise<HomepageQuoteSettings> {
  const settings = await prisma.homepageQuoteSettings.findFirst({ orderBy: { createdAt: "asc" } });
  if (!settings) return fallbackSettings;

  return {
    isQuoteCardVisible: settings.isQuoteCardVisible,
    isAutoGenerateActive: settings.isAutoGenerateActive,
    manualQuoteText: settings.manualQuoteText,
    manualQuoteAuthor: settings.manualQuoteAuthor,
  };
}

export async function updateHomepageQuoteSettings(input: HomepageQuoteSettingsInput) {
  const data = homepageQuoteSettingsSchema.parse(input);
  const current = await prisma.homepageQuoteSettings.findFirst({ orderBy: { createdAt: "asc" } });
  cachedQuote = null;

  if (current) {
    return prisma.homepageQuoteSettings.update({ where: { id: current.id }, data });
  }

  return prisma.homepageQuoteSettings.create({ data });
}

async function fetchDummyJsonQuote(): Promise<ResolvedQuote> {
  const response = await fetch("https://dummyjson.com/quotes/random", { cache: "no-store" });
  if (!response.ok) throw new Error("QUOTE_FETCH_FAILED");
  const data = await response.json() as { quote?: unknown; author?: unknown };
  if (typeof data.quote !== "string" || typeof data.author !== "string") throw new Error("QUOTE_FETCH_INVALID");
  return { text: data.quote, author: data.author };
}

async function translateQuoteWithMyMemory(quote: ResolvedQuote): Promise<ResolvedQuote> {
  const url = new URL("https://api.mymemory.translated.net/get");
  url.searchParams.set("q", quote.text);
  url.searchParams.set("langpair", "en|pt-BR");
  const response = await fetch(url, { cache: "no-store" });
  if (!response.ok) throw new Error("TRANSLATION_FETCH_FAILED");
  const data = await response.json() as { responseData?: { translatedText?: unknown } };
  const translatedText = data.responseData?.translatedText;
  if (typeof translatedText !== "string" || translatedText.trim().length < 3) throw new Error("TRANSLATION_FETCH_INVALID");
  return { text: translatedText.trim(), author: quote.author };
}

export async function getHomepageQuoteCard(options: HomepageQuoteResolverOptions = {}): Promise<HomepageQuoteCardData | null> {
  const now = options.now ?? Date.now();
  const settings = await (options.settings ?? getHomepageQuoteSettings)();

  if (!settings.isQuoteCardVisible) return null;
  if (!settings.isAutoGenerateActive) return manualQuote(settings);
  if (cachedQuote && cachedQuote.expiresAt > now) return cachedQuote.quote;

  try {
    const fetchExternalQuote = options.fetchExternalQuote ?? fetchDummyJsonQuote;
    const translateToPortuguese = options.translateToPortuguese ?? translateQuoteWithMyMemory;
    const quote = await translateToPortuguese(await fetchExternalQuote());
    const resolved = { ...quote, isAutoGenerated: true };
    cachedQuote = { quote: resolved, expiresAt: now + HOMEPAGE_QUOTE_CACHE_MS };
    return resolved;
  } catch {
    return manualQuote(settings);
  }
}
